### ISSUE TITLE
errata: 6.6 page 188 - remove agent forwarding

### ISSUE THREAD

**Issue by UzK98fYoE** [AWSinAction/code2#42]
Please remove the agent forwarding section, which has well-known exploits, as mentioned in `man ssh-agent` ("This method is easily abused by root or another instance of the same user.") . Instead, please use proxy jump. Details are here: https://smallstep.com/blog/ssh-agent-explained/

"If you're trying to access internal hosts through a bastion, ProxyJump is a much safer alternative for this use case."

**Comment by UzK98fYoE** [comment]
I see that you already address this as an afterthought with "Using agent forwarding is a security risk." It's probably more secure to remove the agent-forwarding discussion and demonstrate with the proxy jump instead.

**Comment by michaelwittig** [comment]
Hi @UzK98fYoE 

Thanks for your comment. As you mentioned, the box that follows the example uses the `-J` option for ProxyJump.

If I remember correctly, we kept the two step approach in the book because it shows very clearly what happens and makes it easier to understand what's going on. But I agree that we should revisit this pattern in a future edition.

**Comment by michaelwittig** [comment]
And btw @UzK98fYoE , thanks for reading our book so carefully!
