### ISSUE TITLE
Issues with nodecc

### ISSUE THREAD

**Issue by hellmersjl3ds** [AWSinAction/code2#9]
Are you looking for help with this code for the next edition?  I was working through the first Edition and I saw there was a new version of nodecc so I tried it out.  I had some problems that maybe I can help you address.

**Comment by michaelwittig** [comment]
Hi @hellmersjl3ds 
What issues have you experienced?

PS: nodecc created a log file in the same directory called `nodecc.log` which contains debug information.

**Comment by hellmersjl3ds** [comment]
I just get a blank screen.

I had to change the region to the one where I do everything in the various js files I'm using.

I don't have a default VPC in the region I'm using.

The log just shows

`LOG: open(1)
-`

**Comment by michaelwittig** [comment]
We try to keep things simple in the book, that's why we select defaults:
* We use us-east-1 in the book 
* We ask you to use an AWS account that is new enough to have default VPCs

If you look at the code, `us-east-1` is hardcoded and `lib/listSubnets.js` only lists subnets from your default vpc.

The behaviour is expected.
